### ISSUE TITLE
appDir always references current directory regardless of where Roosevelt is required

### ISSUE THREAD

**Issue by w00tedness** [rooseveltframework/roosevelt#169]
When running a mocha test suite for route testing, the appDir looks for a `package.json` in the current directory of the test file, but we need to look at the root of the project.   

#### Smart Option : 
If Roosevelt ~~somehow detected that it was being called in via a test framework~~ scanned the project directories, `appDir` would point to the correct `package.json` in the root directory of the project. 

#### Less Smart Option: 
It would also be nice if your could pass in the appDir as a param at require()

**Comment by alallier** [comment]
Help me out here if I'm thinking about this if I am thinking to crudely. Right now to check for the appDir we use a (naive? for lack of better of a better word) which checks where roosevelt is required and then keeps grabbing the parent until it finds the `roosevelt.js` and then goes two parents above that. So it regular app cases this is good two parents above the `roosevelt.js` file is the `appDir` but when required outside of that level we have problems. Say two levels down in a test directory. Can we not just use `process.cwd()` since you will always being in the app directory when running commands. So `npm run dev` `process.cwd()` will give the appDir. Running npm test and using `process.cwd()` will set the `appDir` correctly. Then we don't have a hard-coded two step and roosevelt can be required anywhere.

Is there a flaw in this implementation?

**Comment by kethinov** [comment]
pwd will be wrong because if you start the app from a directory that isn't the same as app.js, pwd will be set to whatever your current directory is.

**Comment by alallier** [comment]
Yeah good point didn't think of the case where you could be up a directory and call `/someDir/app.js`, so we will have to use a walk to try and smartly find the appDir.
