### ISSUE TITLE
Arguments broken when using something like PM2

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#340]
Roosevelt won't source arguments when using something like [PM2](https://github.com/Unitech/pm2). This is due to this [block](https://github.com/rooseveltframework/roosevelt/blob/master/lib/sourceFlags.js#L8-L11) of code.

When using PM2 arguments look like this 

```
[ '/usr/bin/node',
  '/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js',
  '--development-mode' ]
```

The source name `app.js` in this case is not in the argument list, so `--development-mode` never gets sourced

**Comment by Autre31415** [comment]
As of right now there is an intentional security check in place that ignores the argument list when Roosevelt is started in an external environment.

The best way to solve this would be to ensure that unit tests always start Roosevelt apps inside of a forked process, to ensure there is no environmental pollution that effects the app. Once this is done we can strip out that check and this issue will be solved.
