### ISSUE TITLE
Find a way to generate certs dynamically for https tests

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/roosevelt#378]

**Comment by kethinov** [comment]
Possible solution: [mkcert](https://github.com/FiloSottile/mkcert)?

Rather than use self-signed OpenSSL certificates, you can create locally-trusted ones for any development domain.

Install local CA: `mkcert -install`

Create certificates for use in web app: `mkcert localhost 127.0.0.1 ::1`

The main benefit: No more SSL warnings! However, it also prevents some weird development quirks where browsers do not cache HTTPS responses because the certificate is invalid.

The local CA may fail to install on Windows Firefox, so:

1. Locate the rootCA.pem file (C:\Users\<name>\AppData\Local\mkcert).
2. In Firefox: menu > Options > find "Certificates" > View Certificates > Authorities tab, click Import..., select rootCA.pem file, import, and restart.

h/t [Craig Buckler](https://twitter.com/craigbuckler/status/1205104238558371842)
