### ISSUE TITLE
Support multiple exceptions in htmlValidator

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/roosevelt#607]
Validator should not trigger on non `res.render`s. In the case of `res.send` (or others) the validator should not trigger because it will always be invalid.

I created a [sample repository](https://github.com/alallier/validator-test) to demo this.

Start the app and hit the `/test` route in _both_ **`dev`** and **`prod`** mode

**Comment by kethinov** [comment]
Some issues with this.

First, I don't think it's possible to exempt `send` from the override directly. I believe in Express, render and send are largely synonymous, so overriding render overrides send too.

Also, there is already a supported/intended way to handle the scenario in the sample app. The intent is for users to declare `exceptions` in `htmlValidator` (see [docs](https://github.com/rooseveltframework/roosevelt) for details) to exempt things like API requests or HTML partials from validation.

The default is:

```
"exceptions": {
  "requestHeader": "Partial",
  "modelValue": "_disableValidator"
}
```

Under this default, if you send a request with the request header "Partial" in it, the validator will not run even when enabled. This allows you to get back markup fragments or JSON without it running through the validator and works today.

While that's a solution you can use now, I can think of two refinements we should add:

1. Multiple exceptions. IIRC the current API only allows one exception despite the API being `exceptions` plural. We should also support passing an array of objects rather than just one object.

2. Whitelist content-types for validation. We should not override render or send if the response content type is not text/html. While I don't believe overriding render but not send is possible, I do think we can sniff for content types. That might a good way to make it possible to handle this scenario in a more flexible way.
