### ISSUE TITLE
Calling render without supplying a model in production mode or when validator is disabled could be a problem

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/roosevelt#675]
[This block](https://github.com/rooseveltframework/roosevelt/blob/8c0d06bb8575231779586669e2dde1bfb90dc6cb/lib/htmlValidator.js#L141-L143) was added to [this PR](https://github.com/rooseveltframework/roosevelt/pull/672) in order to deal with an issue in which calling `res.render()` and supplying a template but not a model (e.g. `res.render('someTemplate')` instead of `res.render('someTemplate', model)`) would crash the app. Presumably there are other scenarios where this could occur as well, such as in production mode or when manually disabling the validator. That should be looked into.

**Comment by Autre31415** [comment]
After testing this I've determined this is not an issue for the following reasons:

- res.render considers the model argument optional https://expressjs.com/en/api.html#res.render
- The validator code referenced in the issue exists because the render override checks values in the model here https://github.com/rooseveltframework/roosevelt/blob/8c0d06bb8575231779586669e2dde1bfb90dc6cb/lib/htmlValidator.js#L151
- I tested it manually and there's no crash
